# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('employee_id', models.IntegerField(verbose_name='employee id')),
                ('wage', models.FloatField(verbose_name='employee wage')),
                ('desired_hours', models.IntegerField(verbose_name='desired weekly hours')),
                ('overtime', models.IntegerField(verbose_name='overtime')),
                ('monthly_medical', models.IntegerField(verbose_name='monthly medical')),
                ('workmans_comp', models.IntegerField(verbose_name='workmans comp')),
                ('social_security', models.IntegerField(verbose_name='social security')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRevenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_total', models.IntegerField(verbose_name='monthly total revenue')),
                ('month_year', models.DateField(verbose_name='month and year')),
            ],
        ),
        migrations.CreateModel(
            name='RepeatUnavailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('weekday', models.IntegerField(verbose_name='weekday')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='start datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='end datetime')),
                ('hide_start_time', models.BooleanField()),
                ('hide_end_time', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Employee'),
        ),
    ]
