# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0002_remove_department_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_for_employee', models.IntegerField(verbose_name='tier for employee')),
                ('seniority', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='name',
        ),
        migrations.AddField(
            model_name='departmentmembership',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Department'),
        ),
        migrations.AddField(
            model_name='departmentmembership',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='members',
            field=models.ManyToManyField(through='schedulingcalendar.DepartmentMembership', to='schedulingcalendar.Employee'),
        ),
    ]
