# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0005_auto_20170119_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime', models.IntegerField(verbose_name='monthly medical')),
                ('workweek_weekday_start', models.IntegerField(verbose_name='weekday')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkWeek',
        ),
    ]
