# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0006_auto_20170120_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmembership',
            name='seniority',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
