# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0007_auto_20170120_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='vacation',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start datetime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='overtime',
            field=models.IntegerField(verbose_name='overtime'),
        ),
    ]
