# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0008_auto_20170124_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='workweek_weekday_start',
            field=models.IntegerField(default=0, verbose_name='weekday'),
        ),
    ]
