# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0009_auto_20170124_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmembership',
            name='seniority',
            field=models.IntegerField(default=0, max_length=64, null=True, verbose_name='seniority'),
        ),
    ]
