# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulingcalendar', '0012_auto_20170405_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesiredTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('weekday', models.IntegerField(verbose_name='weekday')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
