# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0013_desiredtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='workweek_time_start',
            field=models.TimeField(default=None, verbose_name='start_time'),
            preserve_default=False,
        ),
    ]
