# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0014_businessdata_workweek_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='workweek_time_start',
            field=models.TimeField(verbose_name='start time'),
        ),
    ]
