# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0016_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='display_am_pm',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessdata',
            name='display_minutes',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
