# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0018_auto_20170524_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='display_last_names',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
