# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0019_businessdata_display_last_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='display_first_char_last_name',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
