# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0020_businessdata_display_first_char_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdata',
            old_name='display_first_char_last_name',
            new_name='display_first_char_of_last_name',
        ),
    ]
