# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0021_auto_20170530_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='display_am_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='display_first_char_of_last_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='display_last_names',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='display_minutes',
            field=models.BooleanField(default=True),
        ),
    ]
