# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0023_auto_20170530_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='lunch_break_in_min',
            field=models.IntegerField(default=30, verbose_name='Lunch Break'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='overtime',
            field=models.IntegerField(default=40, verbose_name='Overtime'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='overtime_multiplier',
            field=models.FloatField(default=1.5, verbose_name='Overtime Multiplier'),
        ),
    ]
