# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0024_auto_20170530_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdata',
            name='lunch_break_in_min',
        ),
        migrations.AddField(
            model_name='businessdata',
            name='break_time_in_min',
            field=models.IntegerField(default=30, verbose_name='Average Break Length In Minutes Per Schedule'),
        ),
    ]
