# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulingcalendar', '0026_businessdata_min_time_for_break'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='break_time_in_min',
            field=models.IntegerField(default=30, verbose_name='Average Break Length In Minutes Per Eligable Schedule'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='min_time_for_break',
            field=models.FloatField(default=5, verbose_name='Minimum Schedule Duration In Hours For Break Eligability'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='overtime',
            field=models.IntegerField(default=40, verbose_name='Overtime In Hours'),
        ),
    ]
