# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0027_auto_20170617_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='manager_user',
            new_name='user',
        ),
    ]
