# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0028_auto_20170617_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
