# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 16:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0030_auto_20170627_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livecalendar',
            name='date',
        ),
        migrations.AddField(
            model_name='livecalendar',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 28, 16, 29, 44, 210000, tzinfo=utc), verbose_name='Datetime'),
        ),
    ]
