# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0031_auto_20170628_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livecalendar',
            name='datetime',
            field=models.DateTimeField(verbose_name='Datetime'),
        ),
    ]
