# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0033_auto_20170628_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livecalendar',
            name='datetime',
        ),
        migrations.AddField(
            model_name='livecalendar',
            name='date',
            field=models.DateField(default=datetime.date(2017, 6, 28), verbose_name='Date'),
        ),
    ]
