# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 19:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0034_auto_20170628_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='last_cal_date_loaded',
            field=models.DateField(default=datetime.date.today, verbose_name='last_cal_date'),
        ),
        migrations.AddField(
            model_name='businessdata',
            name='last_cal_department_loaded',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Department'),
        ),
        migrations.AlterField(
            model_name='livecalendar',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
