# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0035_auto_20170805_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='last_cal_department_loaded',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Department'),
        ),
    ]
