# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 18:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0037_auto_20170805_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='last_cal_date_loaded',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='last_cal_date'),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='last_cal_department_loaded',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedulingcalendar.Department'),
        ),
    ]
