# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0038_auto_20170818_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='workweek_time_start',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='start time'),
        ),
    ]
