# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-23 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0039_auto_20170822_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='display_nonzero_minutes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='last_cal_department_loaded',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedulingcalendar.Department'),
        ),
    ]
