# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-24 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0041_liveschedule_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveschedule',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedulingcalendar.Schedule'),
        ),
    ]
