# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0042_auto_20171024_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='desired_hours',
            field=models.IntegerField(default=30, verbose_name='desired weekly hours'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(default=0, verbose_name='employee id'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_medical',
            field=models.FloatField(default=0, verbose_name='monthly medical'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_security',
            field=models.FloatField(default=6.2, verbose_name='social security'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage',
            field=models.FloatField(default=0, verbose_name='employee wage'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='workmans_comp',
            field=models.FloatField(default=0, verbose_name='workmans comp'),
        ),
    ]
