# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-31 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0044_auto_20171025_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start datetime'),
        ),
        migrations.AlterField(
            model_name='desiredtime',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='desiredtime',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='liveschedule',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='liveschedule',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start datetime'),
        ),
        migrations.AlterField(
            model_name='repeatunavailability',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='repeatunavailability',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start datetime'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start datetime'),
        ),
    ]
