# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0047_auto_20171106_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='sort_by_eligibles',
            field=models.BooleanField(default=True),
        ),
    ]
