# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0050_daynotebody_daynoteheader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daynotebody',
            name='text',
        ),
        migrations.RemoveField(
            model_name='daynoteheader',
            name='text',
        ),
        migrations.AddField(
            model_name='daynotebody',
            name='body_text',
            field=models.CharField(default='', max_length=280, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='daynoteheader',
            name='header_text',
            field=models.CharField(default='', max_length=140, verbose_name='Note'),
        ),
    ]
