# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0051_auto_20171121_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_note',
            field=models.CharField(default='', max_length=280),
        ),
    ]
