# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0054_businessdata_uniquerowperemployee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdata',
            old_name='uniqueRowPerEmployee',
            new_name='unique_row_per_employee',
        ),
    ]
