# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0060_auto_20180322_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='daynotebody',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Department'),
        ),
        migrations.AddField(
            model_name='daynoteheader',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Department'),
        ),
    ]
