# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0061_auto_20180326_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='override_list_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='unique_row_per_employee',
            field=models.BooleanField(default=True),
        ),
    ]
