# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-10 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0063_employee_see_only_my_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='workweek_weekday_start',
            field=models.IntegerField(default=6, verbose_name='weekday'),
        ),
    ]
