# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulingcalendar', '0066_auto_20180418_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCalendarDepartmentViewRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_view_rights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Department')),
            ],
        ),
        migrations.CreateModel(
            name='LiveCalendarEmployeeViewRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='livecalendar',
            name='all_employees',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monthly_medical',
            field=models.FloatField(default=0, verbose_name='Monthly medical in dollars per month'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_security',
            field=models.FloatField(default=7.5, verbose_name='Social security percentage'),
        ),
        migrations.AddField(
            model_name='livecalendaremployeeviewrights',
            name='employee_view_rights',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Employee'),
        ),
        migrations.AddField(
            model_name='livecalendaremployeeviewrights',
            name='live_calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.LiveCalendar'),
        ),
        migrations.AddField(
            model_name='livecalendaremployeeviewrights',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livecalendardepartmentviewrights',
            name='live_calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.LiveCalendar'),
        ),
        migrations.AddField(
            model_name='livecalendardepartmentviewrights',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livecalendar',
            name='department_view_rights',
            field=models.ManyToManyField(related_name='department_view_rights', through='schedulingcalendar.LiveCalendarDepartmentViewRights', to='schedulingcalendar.Department'),
        ),
        migrations.AddField(
            model_name='livecalendar',
            name='employee_view_rights',
            field=models.ManyToManyField(through='schedulingcalendar.LiveCalendarEmployeeViewRights', to='schedulingcalendar.Employee'),
        ),
    ]
