# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0068_auto_20180430_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livecalendar',
            name='all_employees',
        ),
    ]
