# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0069_remove_livecalendar_all_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='company_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=17, null=True, verbose_name='phone number'),
        ),
    ]
