# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 17:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulingcalendar', '0070_auto_20180505_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='desiredtime',
            name='weekday',
            field=models.IntegerField(default=0, verbose_name='weekday'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='month_year',
            field=models.DateField(default=datetime.date.today, verbose_name='month and year'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='monthly_total',
            field=models.IntegerField(default=0, verbose_name='monthly total revenue'),
        ),
    ]
