# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0071_auto_20180524_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='start datetime'),
        ),
        migrations.AlterField(
            model_name='daynotebody',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='daynoteheader',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='desiredtime',
            name='end_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='desiredtime',
            name='start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='livecalendar',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='livecalendar',
            name='department_view_rights',
            field=models.ManyToManyField(db_index=True, related_name='department_view_rights', through='schedulingcalendar.LiveCalendarDepartmentViewRights', to='schedulingcalendar.Department'),
        ),
        migrations.AlterField(
            model_name='livecalendar',
            name='employee_view_rights',
            field=models.ManyToManyField(db_index=True, through='schedulingcalendar.LiveCalendarEmployeeViewRights', to='schedulingcalendar.Employee'),
        ),
        migrations.AlterField(
            model_name='livecalendar',
            name='version',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='liveschedule',
            name='version',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenue',
            name='month_year',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='month and year'),
        ),
        migrations.AlterField(
            model_name='repeatunavailability',
            name='end_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='repeatunavailability',
            name='start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='start datetime'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='start datetime'),
        ),
    ]
