# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-29 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulingcalendar', '0074_auto_20180613_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveCalendarVersionTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(db_index=True, default=1, verbose_name='Version')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.LiveCalendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
