# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-18 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0075_livecalendarversiontimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='display_first_char_last_name_non_unique_first_name',
            field=models.BooleanField(default=False),
        ),
    ]
