# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-30 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulingcalendar', '0078_vacationapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='start datetime')),
                ('end_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='end datetime')),
                ('note', models.CharField(blank=True, default='', max_length=280, verbose_name='Note')),
                ('approved', models.NullBooleanField(default=None)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepeatUnavailabilityApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='start time')),
                ('end_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='end time')),
                ('weekday', models.IntegerField(verbose_name='weekday')),
                ('note', models.CharField(blank=True, default='', max_length=280, verbose_name='Note')),
                ('approved', models.NullBooleanField(default=None)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulingcalendar.Employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
