# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-31 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingcalendar', '0079_absenceapplication_repeatunavailabilityapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenceapplication',
            name='datetime_of_approval',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Datetime of approval'),
        ),
        migrations.AddField(
            model_name='repeatunavailabilityapplication',
            name='datetime_of_approval',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Datetime of approval'),
        ),
        migrations.AddField(
            model_name='vacationapplication',
            name='datetime_of_approval',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Datetime of approval'),
        ),
    ]
